### ISSUE TITLE
Add unit test with Karma and Jasmine...

### ISSUE THREAD

**Issue by liu-kanghui** [anlambert/webpack-gulp-es6-angular-express#3]
Hey Antoine,

I am sorry to bother you again.  
When I try to add karma and jasmine.  it always throws me the error SyntaxError: Use of reserved word 'class'

I would really really really appreciate if you can do another example about adding unit test :) :) :)

Thank you very much!

**Comment by anlambert** [comment]
Hey Kanghui,

I have just updated the repository in order to integrate unit tests for the frontend part of the application using Karma and Jasmine. It was a little tedious to do as the tests must also be bundled through webpack in order to be runnable (as we use es2015 syntax, the tests have also to be transpiled to es5 through babel, that's why you were getting error about the 'class' keyword as it is not part of the legacy es5 standard). Anyway, you should have everything you need to incorporate your own tests to your project. To run the tests, just run `npm run test-frontend` in the root directory of the project. You can also look at the code coverage report (once they have been executed) by opening `coverage/html/index.html` in your browser. 

I will also add unit tests for the backend part of the application later.

Cheers!
