### ISSUE TITLE
error in .less file  when execute npm run test-frontend ...

### ISSUE THREAD

**Issue by liu-kanghui** [anlambert/webpack-gulp-es6-angular-express#6]
Hello Antoine!

So i tried to use less in the project. I change all .css to .less  and add less loader in the webpack

but when i run test-frontend
it throws.

ERROR in ./src/website/app.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (../node_modules/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/website/app.js 12:293-314

not sure what is going on. 
I really appreciate your help !

Thanks 
Kanghui.

**Comment by anlambert** [comment]
Hello Kangui,

I have modified the webpack configuration for the frontend in order to support correctly the import of less files ;-)
The error you had was due to the fact that css imports (but also less or sass files imports) trough webpack are extracted to external css files in production mode (it is recommended to do so in order for your application to load faster) but not in test or watch mode (as we want hot reloading, that's one of the coolest feature with webpack, you can modify your css, less or sass files on the fly while you're testing your application and it will be automatically taken into account without any browser refresh! ). For instance, execute 'npm run start-dev', once the application is compiled, open it in your browser, then modify the file '/src/website/components/parallelcoords/parallelcoords.css' in order to change the color of the lines in the visualization (selector: .foreground path, property: stroke). Save the file, switch to your browser and enjoy the magic :-)

Cheers,
Antoine
